### model
model_name_or_path: baidu/ERNIE-4.5-21B-A3B-Paddle
tensor_parallel_degree: 1
output_dir: None

### server
max_model_len: 131072
port: 8188

### chat
max_new_tokens: 8192
top_p: 0.7
temperature: 0.95

# device
device: npu
