### model
model_name_or_path: baidu/ERNIE-4.5-300B-A47B-Paddle
tensor_parallel_degree: 8
output_dir: None

### server
max_model_len: 16384
port: 8188

### chat
max_new_tokens: 8192
top_p: 0.7
temperature: 0.95

# device
device: xpu