name: Test

on:
  pull_request:
    branches:
      - develop
      - release/v1.0
      - ernie-4.5-vl

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
  
jobs:
  Test:
    name: Test
    runs-on: [self-hosted, ernie-8gpu]
    steps:
      - name: Start Docker 
        run: |
          if [ ! "$(docker ps -q -f name=ERNIE_CI_Test)" ]; then
            echo "Starting Test ERNIE_CI_Test"
            docker start ERNIE_CI_Test
          else
            echo "ERNIE_CI_Test already running"
          fi
      - name: Cleanup Environment Cache
        run: docker exec -t ERNIE_CI_Test /bin/bash -c '
          rm -rf /workspace/* /workspace/.[!.]* /workspace/..?*'
      - name: Get Repo
        env:
          ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
          ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
          ACTIONS_ALLOW_UNSECURE_NODE_VERSION: true
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare Model
        run: docker exec -t ERNIE_CI_Test /bin/bash -c ' cp -r /home/models/* /workspace '
      - name: Install erniekit
        run: docker exec -t ERNIE_CI_Test /bin/bash -c '
          pip install -e.'
      - name: Runing case
        run: docker exec -t ERNIE_CI_Test /bin/bash -c '
          make gpu_ci_test'
